name: Auto versioning and Set Latest Tag

on:
  push:
    branches:
      - main # Or the branch you want to auto-version

jobs:
  build:
    name: Create Release and Set Tag
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Auto versioning
      - name: Auto versioning
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch # default type of bump, can be one of: major, minor, patch
          RELEASE_BRANCHES: main # Changed to testing since that's the branch this workflow triggers on

      # Step 3: Set full git describe output as an environment variable
      - name: Set git describe output as env variable
        run: |
          GIT_DESCRIBE_OUTPUT=$(git describe --tags)
          echo "VITE_GIT_DESCRIBE_OUTPUT=$GIT_DESCRIBE_OUTPUT" >> $GITHUB_ENV

      - name: Print GIT_DESCRIBE_OUTPUT
        run: echo ${{ env.VITE_GIT_DESCRIBE_OUTPUT }}

      # Step 4: Update Vercel Environment Variable
      - name: Set git describe output for Vercel
        run: |
          curl -X POST "https://api.vercel.com/v10/projects/$VERCEL_PROJECT_ID/env?upsert=true" \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "key": "VITE_GIT_DESCRIBE_OUTPUT",
              "value": "'"${{ env.VITE_GIT_DESCRIBE_OUTPUT }}"'",
              "type": "plain",
              "target": ["production"],
              "comment": "Updating version number"
            }'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: "prj_UvM6m13CfQSTM3kdhKTgxwP0aayn" # Your Vercel project's ID

# this is the update route instead but it must already exist
# curl -X PATCH "https://api.vercel.com/v9/projects/prj_hxy6qsKh9ugPTmDzkUFpZaG8vsH5/env/MzIVqhub1KGZmR5A  -H "Authorization: Bearer MzIVqhub1KGZmR5A" \
# -d '{
# "comment": "Updating version number",
# "type": "plain",
# "value": "3.2.4"
# }'
